GET http://localhost:3001
###
GET http://localhost:3001/abc
###
POST http://localhost:3001/user/register
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"123456"
}
###
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email":"test3@gmail.com",
    "password":"123456"
}
###
GET http://localhost:3001/user/test-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOWQ5ZTFmYzk1NGZmODMyZDliYzkiLCJpYXQiOjE2NTQzNjcwNTgsImV4cCI6MTY1NDM3MDY1OH0.01XVwBNJN2hje-vfa7d5mzDakWECjny321ZKV9YSVCI
###
POST http://localhost:3001/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjliOWQ5ZTFmYzk1NGZmODMyZDliYzkiLCJpYXQiOjE2NTQzNzEyMTAsImV4cCI6MTY4NTkyODgxMH0.pseWDfLhYECiLxtgv3tSXfYyk-HMrkv5qSzTjuC34co"
}